---
# WELL THIS IS NOT WORKING (YET) ON RAX
- hosts: all
  connection: local
  gather_facts: yes
  pre_tasks:
    # NETWORK CREATION
    - name: Create network on rax
      rax_network:
        username: "{{ username }}"
        api_key: "{{ rax_api_key }}"
        cidr: "{{ encapsulation_network_cidr }}"
        label: "{{ encapsulation_network | default('encapsulation-net') }}"
        state: present
        region: "{{ region_name | default(omit) }}"
      when: cloud_name == "rax"
      delegate_to: localhost
      run_once: True
    - name: Create network on std OS cloud
      os_network:
        availability_zone: "{{ availability_zone | default(omit) }}"
        cloud: "{{ cloud_name }}"
        external: no
        name: "{{ encapsulation_network | default('encapsulation-net') }}"
        region_name: "{{ region_name | default(omit) }}"
        state: present
        wait: yes
      when: cloud_name != "rax"
      delegate_to: localhost
      run_once: True
    - name: Create subnet on std OS cloud
      os_subnet:
        availability_zone: "{{ availability_zone | default(omit) }}"
        cidr: "{{ encapsulation_network_cidr }}"
        cloud: "{{ cloud_name }}"
        enable_dhcp: no
        name: "{{ encapsulation_subnet_name | default('encapsulation-subnet') }}"
        network_name: "{{ encapsulation_network | default('encapsulation-net') }}"
        region_name: "{{ region_name | default(omit) }}"
        state: present
        wait: yes
      when: cloud_name != "rax"
      delegate_to: localhost
      run_once: True
    #NODE CREATION
    - name: Create instances on rax
      rax:
        username: "{{ username }}"
        api_key: "{{ rax_api_key }}"
        flavor: "{{ flavor_name | default('general1-8') }}"
        image: "{{ image_name | default('6d833af9-9e31-4d4e-a4ea-1f7f3a4d4406') }}"
        key_name: "{{ ssh_key_name | default('laptop-rackspace') }}"
        name: "{{ inventory_hostname }}"
        networks:
          - PublicNet
          - "{{ encapsulation_network | default('encapsulation-net') }}"
        region: "{{ region_name | default(omit) }}"
        state: present
      when: cloud_name == "rax"
    - name: Create instances on std OS cloud
      os_server:
        state: present
        name: "{{ inventory_hostname }}"
        cloud: "{{ cloud_name }}"
        image: "{{ image_name | default('6d833af9-9e31-4d4e-a4ea-1f7f3a4d4406') }}"
        key_name: "{{ ssh_key_name | default('laptop-rackspace') }}"
        timeout: 200
        flavor: "{{ flavor_name | default('general1-8') }}"
        nics:
          - net-name: PublicNet
          - net-name: "{{ encapsulation_network | default('encapsulation-net') }}"
      when: cloud_name != "rax"
